#!/bin/sh
#
# reach       Init script for OpenUC Reach
#
# chkconfig: 345 97 15
# description: OpenUC Reach is a skills-based automated contact distribution \
#              system built on Erlang and FreeSWITCH
# processname: reach
# config: sys.config
# config: vm.args

export HOME=/root

start() {
  running=`/usr/lib/reach/bin/reach ping`
  if [[ "$running" == *"not responding to pings"* ]]
  then
      echo "Starting Reach...."
      /usr/lib/reach/bin/reach start >&2
  else
      echo "Reach already running" >&2
  fi
}

case "$1" in
  start)
    start
    ;;
  stop)
    /usr/lib/reach/bin/reach stop
    ;;
  status)
    /usr/lib/reach/bin/reach ping >&2
    ;;
  restart)
    /usr/lib/reach/bin/reach restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac
